# Generated by Django 6.0.7 on 2026-08-18 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_newsarticle_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=250)),
                ('description', models.TextField(blank=True)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Uploaded Video'), ('youtube', 'YouTube Video')], default='image', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='slider/images/')),
                ('video', models.FileField(blank=True, help_text='Upload MP4/WebM video files.', null=True, upload_to='slider/videos/')),
                ('youtube_url', models.URLField(blank=True, help_text='Optional YouTube video URL.')),
                ('poster_image', models.ImageField(blank=True, help_text='Optional preview image for video slides.', null=True, upload_to='slider/posters/')),
                ('button_text', models.CharField(blank=True, max_length=100)),
                ('button_url', models.CharField(blank=True, max_length=250)),
                ('secondary_button_text', models.CharField(blank=True, max_length=100)),
                ('secondary_button_url', models.CharField(blank=True, max_length=250)),
                ('autoplay', models.BooleanField(default=True)),
                ('muted', models.BooleanField(default=True)),
                ('loop_video', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Homepage Slide',
                'verbose_name_plural': 'Homepage Slides',
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='MindTree Technology Solution', max_length=200)),
                ('facebook_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=50)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('secondary_email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('uk_address', models.CharField(blank=True, max_length=300)),
                ('nigeria_address', models.CharField(blank=True, max_length=300)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('biography', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team/')),
                ('linkedin_url', models.URLField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team / Leadership',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
